import { useEffect } from 'react';
import { InnerHero, PublicShell } from '../components/Layout';
import { Reveal } from '../components/Reveal';
import { TLink } from '../components/Curtain';
import { useAccount } from '../lib/account';

export default function Privacy() {
  const { status } = useAccount();
  const tryAquaVisionPath = status === 'in' ? '/workspace' : '/login';

  useEffect(() => {
    document.title = 'Privacy Policy | AquaVision';
  }, []);

  return (
    <PublicShell>
      <InnerHero
        lines={['Privacy', <span className="serif">Policy.</span>]}
        aside="How AquaVision collects, uses, and protects your information when you use our underwater image enhancement platform."
        compact
      />
      <section className="wrap pb-32 md:pb-44">
        <Reveal className="mx-auto max-w-4xl space-y-12 text-[16px] leading-relaxed text-body">
          {/* Metadata banner */}
          <div className="rounded-2xl border border-line bg-surface p-6 sm:p-8">
            <p className="text-sm text-large">
              <strong className="text-head">Effective Date:</strong> October 1, 2026
            </p>
            <p className="mt-2 text-sm text-large">
              <strong className="text-head">Platform:</strong> AquaVision Underwater Image Enhancement
            </p>
          </div>

          {/* 1. Introduction */}
          <div>
            <h2 className="text-[28px] font-medium tracking-tight text-head mb-4">1. Introduction</h2>
            <p>
              AquaVision (&quot;we,&quot; &quot;our,&quot; or &quot;us&quot;) provides AI-powered underwater image color restoration and enhancement services. This Privacy Policy explains what personal data, media files, and operational information we collect, how we process and store this information, and your rights regarding your data when using our web application.
            </p>
            <p className="mt-4">
              By registering an account or accessing AquaVision services, you acknowledge the data practices described in this policy.
            </p>
          </div>

          {/* 2. Information We Collect */}
          <div>
            <h2 className="text-[28px] font-medium tracking-tight text-head mb-4">2. Information We Collect</h2>
            <p>We collect information required to operate user accounts, process underwater images, and maintain platform security:</p>
            <ul className="mt-4 list-disc space-y-2 pl-6 text-body">
              <li>
                <strong className="text-head">Account Identity Information:</strong> Email address, optional display name, profile avatar URL, and account creation timestamps.
              </li>
              <li>
                <strong className="text-head">Authentication Credentials:</strong> Hashed password credentials for email accounts, or basic Google profile identity data when authenticating via Google OAuth 2.0.
              </li>
              <li>
                <strong className="text-head">Uploaded Media Files:</strong> Underwater image files (JPEG or PNG format up to 20MB) uploaded directly for processing.
              </li>
              <li>
                <strong className="text-head">Generated Enhancements:</strong> Enhanced image outputs generated by our machine learning pipelines.
              </li>
              <li>
                <strong className="text-head">Project &amp; Usage Metadata:</strong> Filenames, image dimensions, enhancement operation statuses, share token associations, daily/monthly credit balances, and transaction logs.
              </li>
            </ul>
          </div>

          {/* 3. Google Sign-In & User Data */}
          <div>
            <h2 className="text-[28px] font-medium tracking-tight text-head mb-4">3. Google Sign-In &amp; User Data</h2>
            <p>
              AquaVision supports user sign-in via Google OAuth 2.0. When you authenticate using Google, we request access only to your basic identity profile (email address, full name, and profile picture).
            </p>
            <div className="mt-4 rounded-xl border border-line bg-surface/50 p-6 space-y-3">
              <p className="text-head font-medium">How we use Google User Data:</p>
              <ul className="list-disc space-y-1.5 pl-6 text-sm text-body">
                <li>To authenticate your identity and log you into your AquaVision account.</li>
                <li>To associate your enhanced project history and credit balance with your email address.</li>
                <li>To display your display name and avatar inside your user profile.</li>
              </ul>
              <p className="mt-3 text-sm text-large">
                <strong className="text-head">Scope Restrictions:</strong> We do NOT request or access Gmail messages, Google Drive files, Google Photos, Google Contacts, Google Calendar, or any other sensitive Google APIs. We do NOT store Google OAuth access tokens or refresh tokens in your browser.
              </p>
            </div>
          </div>

          {/* 4. Uploaded Images & AI Processing */}
          <div>
            <h2 className="text-[28px] font-medium tracking-tight text-head mb-4">4. Uploaded Images &amp; AI Image Processing</h2>
            <p>
              When you upload an underwater image to the AquaVision Workspace:
            </p>
            <ul className="mt-4 list-disc space-y-2 pl-6 text-body">
              <li>
                <strong className="text-head">Processing Boundary:</strong> Uploaded binary buffers are sent to our dedicated private machine learning inference service for color restoration and contrast correction.
              </li>
              <li>
                <strong className="text-head">Inference Execution:</strong> Processing runs in memory using PyTorch deep neural network models (`AquaVisionModel` U-Net architecture). High-resolution images exceeding 1024px are processed using 512x512 overlapping tiled inference.
              </li>
              <li>
                <strong className="text-head">No Model Training:</strong> Your uploaded images are used strictly to perform the image enhancement requested by you. Uploaded images are NOT used to train or refine public AI models.
              </li>
            </ul>
          </div>

          {/* 5. Storage & Asset Protection */}
          <div>
            <h2 className="text-[28px] font-medium tracking-tight text-head mb-4">5. Storage &amp; Asset Protection</h2>
            <p>
              Original uploaded images and enhanced results are stored in private cloud storage storage buckets (`Enhanced Files` bucket managed via Supabase).
            </p>
            <ul className="mt-4 list-disc space-y-2 pl-6 text-body">
              <li>
                <strong className="text-head">Private Bucket Access:</strong> Storage objects are stored under restricted paths (`Enhanced Files/{'{user_id}'}/{'{project_id}'}/...`). Storage object access is enforced using database Row Level Security (RLS) policies.
              </li>
              <li>
                <strong className="text-head">Authenticated Proxy Streaming:</strong> Original and enhanced images are not publicly listed on open storage URLs. Asset binaries are streamed directly to authenticated owners through secure backend proxy endpoints.
              </li>
            </ul>
          </div>

          {/* 6. Public Link Sharing */}
          <div>
            <h2 className="text-[28px] font-medium tracking-tight text-head mb-4">6. Public Link Sharing</h2>
            <p>
              You may explicitly generate a public share link for any enhanced project. When a share link is generated:
            </p>
            <ul className="mt-4 list-disc space-y-2 pl-6 text-body">
              <li>A unique, unguessable cryptographic token is associated with the project.</li>
              <li>Anyone possessing the active share URL (`/share/{'{token}'}`) can view the before/after comparison and download the assets.</li>
              <li>You may revoke a share link at any time from your Workspace or History page. Revocation immediately disables public token access.</li>
            </ul>
          </div>

          {/* 7. Cookies & Session Management */}
          <div>
            <h2 className="text-[28px] font-medium tracking-tight text-head mb-4">7. Cookies &amp; Session Management</h2>
            <p>
              AquaVision uses essential HTTP-only cookies for session authentication and security:
            </p>
            <div className="mt-4 overflow-x-auto rounded-xl border border-line">
              <table className="w-full text-left text-sm">
                <thead className="bg-surface border-b border-line text-head">
                  <tr>
                    <th className="p-4">Cookie Name</th>
                    <th className="p-4">Type</th>
                    <th className="p-4">Purpose</th>
                    <th className="p-4">Expiry</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-line text-body">
                  <tr>
                    <td className="p-4 font-mono text-head">sb_access_token</td>
                    <td className="p-4">HTTP-Only, Secure</td>
                    <td className="p-4">Stores JWT session access token for authenticated API requests</td>
                    <td className="p-4">7 days</td>
                  </tr>
                  <tr>
                    <td className="p-4 font-mono text-head">sb_refresh_token</td>
                    <td className="p-4">HTTP-Only, Secure</td>
                    <td className="p-4">Maintains authentication session persistence</td>
                    <td className="p-4">7 days</td>
                  </tr>
                  <tr>
                    <td className="p-4 font-mono text-head">sb_code_verifier</td>
                    <td className="p-4">HTTP-Only, Secure</td>
                    <td className="p-4">Stores temporary cryptographic PKCE verifier during OAuth initiation</td>
                    <td className="p-4">10 minutes</td>
                  </tr>
                </tbody>
              </table>
            </div>
            <p className="mt-4 text-sm text-large">
              We do NOT use third-party tracking cookies or advertising pixels. Authentication tokens are never stored in browser `localStorage` or `sessionStorage`.
            </p>
          </div>

          {/* 8. Email Communications & OTP */}
          <div>
            <h2 className="text-[28px] font-medium tracking-tight text-head mb-4">8. Email Communications &amp; One-Time Passwords (OTP)</h2>
            <p>
              When signing up or resetting your password, transactional email messages containing 6-digit verification codes are delivered via Nodemailer SMTP.
            </p>
            <ul className="mt-4 list-disc space-y-2 pl-6 text-body">
              <li>OTP verification codes expire automatically after 10 minutes.</li>
              <li>Verification codes are stored in our database strictly as salted cryptographic SHA-256 hashes.</li>
              <li>Transactional emails are sent exclusively for account verification, password recovery, or essential service alerts. We do not send marketing spam.</li>
            </ul>
          </div>

          {/* 9. Third-Party Infrastructure Services */}
          <div>
            <h2 className="text-[28px] font-medium tracking-tight text-head mb-4">9. Third-Party Infrastructure Services</h2>
            <p>AquaVision integrates with trusted infrastructure providers to deliver our application:</p>
            <ul className="mt-4 list-disc space-y-2 pl-6 text-body">
              <li><strong className="text-head">Supabase Inc.:</strong> Cloud database hosting (PostgreSQL), authentication services, and private object storage (`Enhanced Files`).</li>
              <li><strong className="text-head">Google LLC:</strong> Identity authentication via Google OAuth 2.0.</li>
              <li><strong className="text-head">Cloudflare Inc.:</strong> Edge network CDN distribution and domain routing.</li>
              <li><strong className="text-head">Nodemailer / SMTP Transport:</strong> Delivery of transactional account verification emails.</li>
            </ul>
          </div>

          {/* 10. Data Retention & Deletion */}
          <div>
            <h2 className="text-[28px] font-medium tracking-tight text-head mb-4">10. Data Retention &amp; Deletion</h2>
            <p>
              Your project data and uploaded files remain in your account until you choose to delete them.
            </p>
            <ul className="mt-4 list-disc space-y-2 pl-6 text-body">
              <li>
                <strong className="text-head">User-Initiated Project Deletion:</strong> When you delete a project from your Workspace or History page (or execute multi-select bulk delete), the project database entry, linked share tokens, and underlying original and enhanced files in private Supabase Storage are permanently and irrevocably deleted.
              </li>
              <li>
                <strong className="text-head">Account Deletion:</strong> You may request full account deletion by contacting support. Account deletion removes all associated profile data, project histories, and stored files.
              </li>
            </ul>
          </div>

          {/* 11. Security Measures */}
          <div>
            <h2 className="text-[28px] font-medium tracking-tight text-head mb-4">11. Security Measures</h2>
            <p>
              We enforce industry-standard security controls to safeguard your data, including HTTPS transport encryption, Row Level Security (RLS) policies on database and storage objects, rate limiting on authentication routes, account lockout protections against brute-force password/OTP attempts, and HTTP-only session cookie isolation against cross-site scripting (XSS).
            </p>
          </div>

          {/* 12. Children's Privacy */}
          <div>
            <h2 className="text-[28px] font-medium tracking-tight text-head mb-4">12. Children&apos;s Privacy</h2>
            <p>
              AquaVision is not directed to individuals under 13 years of age. We do not knowingly collect personal information from children. If you become aware that a child has provided us with personal data, please contact us to have the data removed.
            </p>
          </div>

          {/* 13. Changes to This Policy */}
          <div>
            <h2 className="text-[28px] font-medium tracking-tight text-head mb-4">13. Changes to This Privacy Policy</h2>
            <p>
              We may update this Privacy Policy from time to time to reflect changes in our services or technical architecture. Any updates will be posted on this page with a revised effective date.
            </p>
          </div>

          {/* 14. Contact Information */}
          <div className="rounded-2xl border border-line bg-surface p-6 sm:p-8">
            <h2 className="text-[24px] font-medium tracking-tight text-head mb-3">14. Contact Information</h2>
            <p className="text-body">
              If you have any questions, concerns, or requests regarding this Privacy Policy or your data, please contact us at:
            </p>
            <p className="mt-4 font-mono text-head">
              [AquaVision Contact Email]
            </p>
          </div>

          {/* Back link */}
          <div className="border-t border-line pt-8">
            <TLink to={tryAquaVisionPath} className="ulink is-on inline-flex items-center gap-2 text-head">
              ← Back to AquaVision
            </TLink>
          </div>
        </Reveal>
      </section>
    </PublicShell>
  );
}